I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/animation.rpy", line 1, in script
    init python:
  File "game/animation.rpy", line 1, in script
    init python:
  File "game/animation.rpy", line 12, in <module>
    image_animation('image_name.png', [(1, 'image_name.png'), (1, 'image_name_2.png'), (1, 'image_name_3.png')])
  File "game/animation.rpy", line 5, in image_animation
    image_show(image)  # отображаем изображение
NameError: global name 'image_show' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 331, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 560, in main
    renpy.game.context().run(node)
  File "game/animation.rpy", line 1, in script
    init python:
  File "game/animation.rpy", line 1, in script
    init python:
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/animation.rpy", line 12, in <module>
    image_animation('image_name.png', [(1, 'image_name.png'), (1, 'image_name_2.png'), (1, 'image_name_3.png')])
  File "game/animation.rpy", line 5, in image_animation
    image_show(image)  # отображаем изображение
NameError: global name 'image_show' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Alex 1.0
Sun Feb 19 19:40:08 2023
